---
- hosts: all
  become: no
  gather_facts: yes
  tasks:
  - name: "Populate service facts"
    service_facts:
  - name: "See the service facts as they are"
    debug:
      msg: "{{ansible_facts.services}}"